version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\projects\src\github.com\rjeczalik\interfaces

environment:
 PATH: c:\projects\bin;%PATH%
 GOPATH: c:\projects

install:
 - cd %APPVEYOR_BUILD_FOLDER%
 - go version
 - go get golang.org/x/tools/cmd/vet
 - go get -v -t ./...

build_script:
 - go tool vet -all .
 - go build ./...
 - go test -race -v ./...

test: off

deploy: off

